# Generated by Django 2.1.2 on 2018-11-24 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_role_rolegroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolegroup',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.Role'),
        ),
        migrations.AlterField(
            model_name='rolegroup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.User'),
        ),
    ]
